### ISSUE TITLE
why do you have a develop-2 branch?

### ISSUE THREAD

**Issue by cordoval** [auraphp/Aura.Cli#26]
could you please describe the branching model you are using? thanks :baby:

**Comment by harikt** [comment]
@cordoval 
`develop` is version 1. 
`master` is the current release. 
`develop-2` is version 2.

Hope that makes sense.

**Comment by cordoval** [comment]
it would make more sense to label them as v1 and v2. Do you mean master is ahead of develop-2? 

I am sorry I am still confused :cry:

**Comment by harikt** [comment]
Hi @cordoval master is v1.

I agree when people are new to here, they don't probably get it. May be we can discuss the problem in google groups if you are interested to get this resolved. ( We can hear the voice of the larger audience )

**Comment by pmjones** [comment]
In the library packages, "master" is supposed to be the most-recent stable release, and "develop" is where the v1 development goes. Similarly, "develop-2" is where v2 development goes. In future, we may get rid of "master" entirely, and go only with "develop*" branches, leaving releases (stable and otherwise) to tags.

**Comment by cordoval** [comment]
yeah i believe we should not support branches, i mean encouraging better to upgrade in this situation is desired. :+1:
