### ISSUE TITLE
Why do we need to pass stdin , stdout and stderr ?

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Cli#4]
Hi @pmjones ,

I wonder why we need to pass `php://stdin` , `php://stdout`, `php://stderr` as we already have the constants and utilize it ?

```
new Stdio(
    fopen('php://stdin', 'r'),
    fopen('php://stdout', 'w+'),
    fopen('php://stderr', 'w+'),
    new Vt100
),
```

I was looking over http://www.php.net/manual/en/features.commandline.io-streams.php

Thanks 

Hari K T

**Comment by pmjones** [comment]
I used the constants originally, but they seem to be the "master" connections; closing them makes them impossible to reuse, which turned out to be important during testing.  For example, if you use STDIN and then close it later, you can't re-open it.  You can pass STDIN/STDOUT/STDERR _if you like_ but I think it's accident-prone.

**Comment by harikt** [comment]
Yes understood :-) .
